name: Playwright tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set environment variables for app
        run: scripts/ci/copy-env-vars-to-dot-env-file
        env:
          NUXT_R_API_BASE: ${{ vars.NUXT_R_API_BASE }}
          # Note - non-secret variables are stored under the 'vars' context, while secrets will be stored under the 'secrets' context
      - name: Run service dependencies
        run: scripts/run-dependencies
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - name: Install npm dependencies
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps && npx playwright install msedge
      - name: Run Playwright tests
        run: npm run test:e2e
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
