name: Playwright Tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run deps
        run: scripts/run-dependencies
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Build app
        run: npm run build
      - name: Start app in production mode
        run: NITRO_HOST="127.0.0.1" NITRO_PORT="3000" npm run preview
      - name: Install Playwright browsers
        run: npx playwright install --with-deps && npx playwright install msedge
      - name: Run Playwright tests
        run: npm run test:e2e
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
